module "vultr-instances" {
  source = "../../modules/vultr-instance"

  plan = "vc2-1c-1gb"
  region = "lhr"
  os_id = 477
  label = "Baby Yoda Bot"
  tags = ["Baby Yoda Bot", "Test", "Version: 0.0.1"]
  hostname = "baby-yoda-bot"
  api_key = var.api_key
  start_up_script = "IyEvYmluL2Jhc2gKc2V0IC1lCgpzdWRvIGFwdC1nZXQgdXBkYXRlIC15CgplY2hvICcjIyMjIyMgSW5zdGFsbGluZyBHaXQgIyMjIyMjIycKc3VkbyBhcHQtZ2V0IGluc3RhbGwgZ2l0IC15CgplY2hvICcjIyMjIyMgSW5zdGFsbGluZyBwaXAgIyMjIyMjJwpzdWRvIGFwdC1nZXQgaW5zdGFsbCBweXRob24zLXBpcCAteQoKZWNobyAnIyMjIyMjIEluc3RhbGxpbmcgRGlzY29yZCBFeHQgTWVudXMgIyMjIyMjJwpwaXAgaW5zdGFsbCAtVSBnaXQraHR0cHM6Ly9naXRodWIuY29tL1JhcHB0ei9kaXNjb3JkLWV4dC1tZW51cwoKZWNobyAnIyMjIyMjIEluc3RhbGxpbmcgQXAgU2NoZWR1bGVyICMjIyMjIycKcGlwIGluc3RhbGwgYXBzY2hlZHVsZXIKCmVjaG8gJyMjIyMjIyBJbnN0YWxsaW5nIERpc2NvcmQucHkgIyMjIyMjJwpwaXAgaW5zdGFsbCBkaXNjb3JkLnB5CgplY2hvICcjIyMjIyMgSW5zdGFsbGluZyBUbXV4ICMjIyMjIycKc3VkbyBhcHQtZ2V0IGluc3RhbGwgdG11eCAteQoKZWNobyAnIyMjIyMjIENvcHlpbmcgUHVibGljIEtleSB0byBhdXRob3JpemVkX2tleXMgIyMjIyMjJwplY2hvICJzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJnUUMzSzVIQnNxdExNTElxd1NuQzJwa2pLbTRtSmhSK2tRVDZUbE9YMjBCRnROejFVa0tySmtGdWt2cSt2b1czRkpGNm5uWFlpSzZaWEtXMFdLbGl1ZHEyZ1MrSmtCaWVhamJJb0FKb0YrYVBZWFZBMHozT1JTdTVnbVlkVlh4bURuaTBQenUzTlFicXZmcnBDVnRmMkpFUkt2UmVpcEJPc1dNdDJuRHBRb2RCYkMvSHo1d3REam1iaEhkNUFiVWZHcSttSTJ4eFhUeXBFd2xkSDNWQWNISHYzUkJKVEkxWGlGN1dHR0hPVVdJLzRLcnZyUXVzOFFlZFRteGdvMExyck9wc0loNTRqQUhLVEhoc3hMdzVXdzZkOHlxS2hSaVcvaStRZzhmK1daNE9OZC85NEFyeDRtYk9kSG5nR29TNHdzRzM0OVdFWUpScTNvN1p5NXE1WTZSdFZtYmF2c0ZBM3ZLMDN1Q3hRTkJCamZiUjdxMTkwdUJMcjJQZC9ZYzRlYUFBbmNCbVgrSkdwZHE5VjdTVExnQXA5YnA3YzZUeXNJR2pyazJlVmo5enZiYVd1ZjBzVTkyVmZ4bW9JcHZwOTBwaG8wVjdrRDhOamRhMk1IVjBXSGZHSEZodG5ITjJ6WUs3dzBpRS9kSkkvNXNjd2M1aFFiZXBhQTZaNGdjaElEcz0gSGVucnkua29sZW9zb0BrZW5zYWxmc3MtTWFjQm9vay1Qcm8ubG9jYWwiID4+IC9yb290Ly5zc2gvYXV0aG9yaXplZF9rZXlz"
}